apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfrog
  namespace: jfrog-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: pd-standard
